package com.ashwini.test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class panelist_bus_dim implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public panelist_bus_dim() {
    }




}