package com.ashwini.test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class test_dataObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer field1;
	private java.lang.String field2;
	private java.lang.String field3;

	public test_dataObject() {
	}

	public java.lang.Integer getField1() {
		return this.field1;
	}

	public void setField1(java.lang.Integer field1) {
		this.field1 = field1;
	}

	public java.lang.String getField2() {
		return this.field2;
	}

	public void setField2(java.lang.String field2) {
		this.field2 = field2;
	}

	public java.lang.String getField3() {
		return this.field3;
	}

	public void setField3(java.lang.String field3) {
		this.field3 = field3;
	}

	public test_dataObject(java.lang.Integer field1, java.lang.String field2,
			java.lang.String field3) {
		this.field1 = field1;
		this.field2 = field2;
		this.field3 = field3;
	}

}