package com.ashwini.test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class test_dataObject implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public test_dataObject() {
    }




}